package presentacion.controlador;

public enum Evento {

	// VISTAS GENERALES
	VISTA_PRINCIPAL,

	// MODELO
	VISTA_MODELO,

	ALTA_MODELO, VISTA_ALTA_MODELO, VISTA_EXITO_ALTA_MODELO, VISTA_FALLO_ALTA_MODELO,

	BAJA_MODELO, VISTA_BAJA_MODELO, VISTA_EXITO_BAJA_MODELO, VISTA_FALLO_BAJA_MODELO,

	CONSULTAR_MODELO_POR_ID, VISTA_CONSULTAR_MODELO_POR_ID, VISTA_RESULTADO_CONSULTAR_MODELO_POR_ID,

	CONSULTAR_TODOS_MODELOS, VISTA_RESULTADO_CONSULTAR_TODOS_MODELOS,

	MODIFICAR_MODELO, MODIFICAR_MODELO_ID, VISTA_MODIFICAR_MODELO_ID, VISTA_MODIFICAR_MODELO, VISTA_EXITO_MODIFICAR_MODELO, VISTA_FALLO_MODIFICAR_MODELO,

	VINCULAR_MODELO, VISTA_VINCULAR_MODELO, VISTA_EXITO_VINCULAR_MODELO, VISTA_FALLO_VINCULAR_MODELO,

	DESVINCULAR_MODELO, VISTA_DESVINCULAR_MODELO, VISTA_EXITO_DESVINCULAR_MODELO, VISTA_FALLO_DESVINCULAR_MODELO,

	CONSULTAR_MODELOS_POR_AEROLINEA, VISTA_CONSULTAR_MODELOS_POR_AEROLINEA, VISTA_RESULTADO_CONSULTAR_MODELOS_POR_AEROLINEA,

	// AVION
	VISTA_AVION,

	ALTA_AVION, VISTA_ALTA_AVION, VISTA_EXITO_ALTA_AVION, VISTA_FALLO_ALTA_AVION,

	BAJA_AVION, VISTA_BAJA_AVION, VISTA_EXITO_BAJA_AVION, VISTA_FALLO_BAJA_AVION,

	CONSULTAR_AVION_POR_ID, VISTA_CONSULTAR_AVION_POR_ID, VISTA_RESULTADO_CONSULTAR_AVION_POR_ID,

	CONSULTAR_TODOS_AVIONES, VISTA_RESULTADO_CONSULTAR_TODOS_AVIONES,

	MODIFICAR_AVION, MODIFICAR_AVION_ID, VISTA_MODIFICAR_AVION, VISTA_MODIFICAR_AVION_ID, VISTA_EXITO_MODIFICAR_AVION, VISTA_FALLO_MODIFICAR_AVION,

	CONSULTAR_AVIONES_POR_MODELO, VISTA_CONSULTAR_AVIONES_POR_MODELO, VISTA_RESULTADO_CONSULTAR_AVIONES_POR_MODELO,

	CONSULTAR_AVIONES_POR_AEROLINEA, VISTA_CONSULTAR_AVIONES_POR_AEROLINEA, VISTA_RESULTADO_CONSULTAR_AVIONES_POR_AEROLINEA,

	CONSULTAR_AVIONES_POR_HANGAR, VISTA_CONSULTAR_AVIONES_POR_HANGAR, VISTA_RESULTADO_CONSULTAR_AVIONES_POR_HANGAR,

	CONSULTAR_AVIONES_DE_AEROLINEA_POR_HANGAR, VISTA_CONSULTAR_AVIONES_DE_AEROLINEA_POR_HANGAR, VISTA_RESULTADO_CONSULTAR_AVIONES_DE_AEROLINEA_POR_HANGAR,

	// AEROL�NEA
	VISTA_AEROLINEA,

	ALTA_AEROLINEA, VISTA_ALTA_AEROLINEA, VISTA_EXITO_ALTA_AEROLINEA, VISTA_FALLO_ALTA_AEROLINEA,

	BAJA_AEROLINEA, VISTA_BAJA_AEROLINEA, VISTA_EXITO_BAJA_AEROLINEA, VISTA_FALLO_BAJA_AEROLINEA,

	CONSULTAR_AEROLINEA_POR_ID, VISTA_CONSULTAR_AEROLINEA_POR_ID, VISTA_RESULTADO_CONSULTAR_AEROLINEA_POR_ID,

	CONSULTAR_TODAS_AEROLINEAS, VISTA_RESULTADO_CONSULTAR_TODAS_AEROLINEAS,

	MODIFICAR_AEROLINEA_ID, MODIFICAR_AEROLINEA, VISTA_MODIFICAR_AEROLINEA_ID, VISTA_MODIFICAR_AEROLINEA, VISTA_EXITO_MODIFICAR_AEROLINEA, VISTA_FALLO_MODIFICAR_AEROLINEA,

	CONSULTAR_AEROLINEAS_POR_MODELO, VISTA_CONSULTAR_AEROLINEAS_POR_MODELO, VISTA_RESULTADO_CONSULTAR_AEROLINEAS_POR_MODELO,

	// CONTRATO
	VISTA_CONTRATO,

	ABRIR_CONTRATO, VISTA_ABRIR_CONTRATO,

	VISTA_CARRITO,

	VISTA_ANYADIR_HANGAR_AL_CONTRATO,

	VISTA_ELIMINAR_HANGAR_AL_CONTRATO,

	CERRAR_CONTRATO, VISTA_EXITO_CERRAR_CONTRATO, VISTA_FALLO_CERRAR_CONTRATO,

	CONSULTAR_CONTRATO_POR_ID, VISTA_CONSULTAR_CONTRATO_POR_ID, VISTA_RESULTADO_CONSULTAR_CONTRATO_POR_ID,

	CONSULTAR_TODOS_CONTRATOS, VISTA_RESULTADO_CONSULTAR_TODOS_CONTRATOS,

	MODIFICAR_CONTRATO, MODIFICAR_CONTRATO_ID, VISTA_MODIFICAR_CONTRATO, VISTA_MODIFICAR_CONTRATO_ID, VISTA_EXITO_MODIFICAR_CONTRATO, VISTA_FALLO_MODIFICAR_CONTRATO,

	MODIFICAR_LINEA_CONTRATO, VISTA_MODIFICAR_LINEA_CONTRATO, VISTA_EXITO_MODIFICAR_LINEA_CONTRATO, VISTA_FALLO_MODIFICAR_LINEA_CONTRATO,

	CONSULTAR_CONTRATOS_POR_AEROLINEA, VISTA_CONSULTAR_CONTRATOS_POR_AEROLINEA, VISTA_RESULTADO_CONSULTAR_CONTRATOS_POR_AEROLINEA,

	CONSULTAR_CONTRATOS_POR_AEROLINEA_PRECIO_Y_DURACION, VISTA_CONSULTAR_CONTRATOS_POR_AEROLINEA_PRECIO_Y_DURACION, VISTA_RESULTADO_CONSULTAR_CONTRATOS_POR_AEROLINEA_PRECIO_Y_DURACION,

	// HANGAR
	VISTA_HANGAR,

	ALTA_HANGAR, VISTA_ALTA_HANGAR, VISTA_EXITO_ALTA_HANGAR, VISTA_FALLO_ALTA_HANGAR,

	BAJA_HANGAR, VISTA_BAJA_HANGAR, VISTA_EXITO_BAJA_HANGAR, VISTA_FALLO_BAJA_HANGAR,

	CONSULTAR_HANGAR_POR_ID, VISTA_CONSULTAR_HANGAR_POR_ID, VISTA_RESULTADO_CONSULTAR_HANGAR_POR_ID,

	CONSULTAR_TODOS_HANGARES, VISTA_RESULTADO_CONSULTAR_TODOS_LOS_HANGARES,

	MODIFICAR_HANGAR, MODIFICAR_HANGAR_ID, VISTA_MODIFICAR_HANGAR, VISTA_MODIFICAR_ID_HANGAR, VISTA_EXITO_MODIFICAR_HANGAR, VISTA_FALLO_MODIFICAR_HANGAR,

	CONSULTAR_HANGARES_POR_PERSONAL, VISTA_CONSULTAR_HANGARES_POR_PERSONAL, VISTA_RESULTADO_CONSULTAR_HANGARES_POR_PERSONAL,

	// PERSONAL
	VISTA_PERSONAL,

	ALTA_PERSONAL, VISTA_ALTA_PERSONAL, VISTA_EXITO_ALTA_PERSONAL, VISTA_FALLO_ALTA_PERSONAL,

	BAJA_PERSONAL, VISTA_BAJA_PERSONAL, VISTA_EXITO_BAJA_PERSONAL, VISTA_FALLO_BAJA_PERSONAL,

	VINCULAR_PERSONAL, VISTA_VINCULAR_PERSONAL, VISTA_EXITO_VINCULAR_PERSONAL, VISTA_FALLO_VINCULAR_PERSONAL,

	DESVINCULAR_PERSONAL, VISTA_DESVINCULAR_PERSONAL, VISTA_EXITO_DESVINCULAR_PERSONAL, VISTA_FALLO_DESVINCULAR_PERSONAL,

	CONSULTAR_PERSONAL_POR_ID, VISTA_CONSULTAR_PERSONAL_POR_ID, VISTA_RESULTADO_CONSULTAR_PERSONAL_POR_ID,

	CONSULTAR_PERSONAL_EXISTENTE, VISTA_RESULTADO_CONSULTAR_PERSONAL_EXISTENTE,

	MODIFICAR_PERSONAL, MODIFICAR_PERSONAL_ID, VISTA_MODIFICAR_PERSONAL, VISTA_MODIFICAR_PERSONAL_ID, VISTA_EXITO_MODIFICAR_PERSONAL, VISTA_FALLO_MODIFICAR_PERSONAL,

	CONSULTAR_PERSONAL_POR_HANGAR, VISTA_CONSULTAR_PERSONAL_POR_HANGAR, VISTA_RESULTADO_CONSULTAR_PERSONAL_POR_HANGAR,

	/////////////////////////////////////////////////////////////

	//MARCA
	VISTA_MARCA,

	ALTA_MARCA, VISTA_ALTA_MARCA, VISTA_EXITO_ALTA_MARCA, VISTA_FALLO_ALTA_MARCA,

	BAJA_MARCA, VISTA_BAJA_MARCA, VISTA_EXITO_BAJA_MARCA, VISTA_FALLO_BAJA_MARCA,

	CONSULTAR_MARCA_POR_ID, VISTA_CONSULTAR_MARCA_POR_ID, VISTA_RESULTADO_CONSULTAR_MARCA_POR_ID,

	CONSULTAR_MARCAS, VISTA_RESULTADO_CONSULTAR_MARCAS,

	MODIFICAR_MARCA, MODIFICAR_MARCA_ID, VISTA_MODIFICAR_MARCA, VISTA_MODIFICAR_ID_MARCA, VISTA_EXITO_MODIFICAR_MARCA, VISTA_FALLO_MODIFICAR_MARCA,

	//PROVEEDOR
	VISTA_PROVEEDOR,

	ALTA_PROVEEDOR, VISTA_ALTA_PROVEEDOR, VISTA_EXITO_ALTA_PROVEEDOR, VISTA_FALLO_ALTA_PROVEEDOR,

	BAJA_PROVEEDOR, VISTA_BAJA_PROVEEDOR, VISTA_EXITO_BAJA_PROVEEDOR, VISTA_FALLO_BAJA_PROVEEDOR,

	CONSULTAR_PROVEEDOR_POR_ID, VISTA_CONSULTAR_PROVEEDOR_POR_ID, VISTA_RESULTADO_CONSULTAR_PROVEEDOR_POR_ID,

	CONSULTAR_PROVEEDORES, VISTA_CONSULTAR_PROVEEDORES, VISTA_RESULTADO_CONSULTAR_PROVEEDORES,

	MODIFICAR_PROVEEDOR, MODIFICAR_PROVEEDOR_ID, VISTA_MODIFICAR_PROVEEDOR_ID, VISTA_MODIFICAR_PROVEEDOR, VISTA_EXITO_MODIFICAR_PROVEEDOR, VISTA_FALLO_MODIFICAR_PROVEEDOR,

	VINCULAR_PROVEEDOR, VISTA_VINCULAR_PROVEEDOR, VISTA_EXITO_VINCULAR_PROVEEDOR, VISTA_FALLO_VINCULAR_PROVEEDOR,

	DESVINCULAR_PROVEEDOR, VISTA_DESVINCULAR_PROVEEDOR, VISTA_EXITO_DESVINCULAR_PROVEEDOR, VISTA_FALLO_DESVINCULAR_PROVEEDOR,

	CONSULTAR_PROVEEDORES_POR_PRODUCTO, VISTA_CONSULTAR_PROVEEDORES_POR_PRODUCTO, VISTA_RESULTADO_CONSULTAR_PROVEEDORES_POR_PRODUCTO,

	//PRODUCTO
	VISTA_PRODUCTO,

	ALTA_PRODUCTO, VISTA_ALTA_PRODUCTO, VISTA_EXITO_ALTA_PRODUCTO, VISTA_FALLO_ALTA_PRODUCTO,

	BAJA_PRODUCTO, VISTA_BAJA_PRODUCTO, VISTA_EXITO_BAJA_PRODUCTO, VISTA_FALLO_BAJA_PRODUCTO,

	CONSULTAR_PRODUCTO_POR_ID, VISTA_CONSULTAR_PRODUCTO_POR_ID, VISTA_RESULTADO_CONSULTAR_PRODUCTO_POR_ID,

	CONSULTAR_PRODUCTOS, VISTA_RESULTADO_CONSULTAR_PRODUCTOS,

	MODIFICAR_PRODUCTO, MODIFICAR_PRODUCTO_ID, VISTA_MODIFICAR_PRODUCTO_ID, VISTA_MODIFICAR_PRODUCTO, VISTA_EXITO_MODIFICAR_PRODUCTO, VISTA_FALLO_MODIFICAR_PRODUCTO,

	CONSULTAR_PRODUCTOS_POR_MARCA, VISTA_CONSULTAR_PRODUCTOS_POR_MARCA, VISTA_RESULTADO_CONSULTAR_PRODUCTOS_POR_MARCA,

	CONSULTAR_PRODUCTOS_POR_PROVEEDOR, VISTA_CONSULTAR_PRODUCTOS_POR_PROVEEDOR, VISTA_RESULTADO_CONSULTAR_PRODUCTOS_POR_PROVEEDOR,

	//VENTA
	VISTA_VENTA,

	ABRIR_VENTA, VISTA_ABRIR_VENTA, //VISTA_EXITO_ABRIR_VENTA, VISTA_FALLO_ABRIR_VENTA,

	VISTA_CARRITO_VENTA,

	VISTA_ANYADIR_PRODUCTO,

	VISTA_ELIMINAR_PRODUCTO,

	CERRAR_VENTA, VISTA_CERRAR_VENTA, VISTA_EXITO_CERRAR_VENTA, VISTA_FALLO_CERRAR_VENTA,

	CONSULTAR_VENTA_POR_ID, VISTA_CONSULTAR_VENTA_POR_ID, VISTA_RESULTADO_CONSULTAR_VENTA_POR_ID,

	CONSULTAR_VENTAS, VISTA_CONSULTAR_VENTAS, VISTA_RESULTADO_CONSULTAR_VENTAS,

	MODIFICAR_VENTA, MODIFICAR_VENTA_ID, VISTA_MODIFICAR_VENTA, VISTA_MODIFICAR_VENTA_ID, VISTA_EXITO_MODIFICAR_VENTA, VISTA_FALLO_MODIFICAR_VENTA,

	MODIFICAR_LINEA_VENTA, VISTA_MODIFICAR_LINEA_VENTA, VISTA_EXITO_MODIFICAR_LINEA_VENTA, VISTA_FALLO_MODIFICAR_LINEA_VENTA,

	CONSULTAR_VENTAS_POR_EMPLEADO, VISTA_CONSULTAR_VENTAS_POR_EMPLEADO, VISTA_RESULTADO_CONSULTAR_VENTAS_POR_EMPLEADO,

	DEVOLUCION_VENTA, VISTA_DEVOLUCION_VENTA, VISTA_EXITO_DEVOLUCION_VENTA, VISTA_FALLO_DEVOLUCION_VENTA,

	//DEPARTAMENTO
	VISTA_DEPARTAMENTO,

	ALTA_DEPARTAMENTO, VISTA_ALTA_DEPARTAMENTO, VISTA_EXITO_ALTA_DEPARTAMENTO, VISTA_FALLO_ALTA_DEPARTAMENTO,

	BAJA_DEPARTAMENTO, VISTA_BAJA_DEPARTAMENTO, VISTA_EXITO_BAJA_DEPARTAMENTO, VISTA_FALLO_BAJA_DEPARTAMENTO,

	CONSULTAR_DEPARTAMENTO_POR_ID, VISTA_CONSULTAR_DEPARTAMENTO_POR_ID, VISTA_RESULTADO_CONSULTAR_DEPARTAMENTO_POR_ID,

	CONSULTAR_DEPARTAMENTOS, VISTA_RESULTADO_CONSULTAR_DEPARTAMENTOS,

	MODIFICAR_DEPARTAMENTO, MODIFICAR_DEPARTAMENTO_ID, VISTA_MODIFICAR_DEPARTAMENTO, VISTA_MODIFICAR_ID_DEPARTAMENTO, VISTA_EXITO_MODIFICAR_DEPARTAMENTO, VISTA_FALLO_MODIFICAR_DEPARTAMENTO,

	CALCULAR_NOMINA, VISTA_CALCULAR_NOMINA, VISTA_EXITO_CALCULAR_NOMINA, VISTA_FALLO_CALCULAR_NOMINA,

	//EMPLEADO
	VISTA_EMPLEADO,

	ALTA_EMPLEADO, VISTA_ALTA_EMPLEADO, VISTA_EXITO_ALTA_EMPLEADO, VISTA_FALLO_ALTA_EMPLEADO,

	BAJA_EMPLEADO, VISTA_BAJA_EMPLEADO, VISTA_EXITO_BAJA_EMPLEADO, VISTA_FALLO_BAJA_EMPLEADO,

	CONSULTAR_EMPLEADO_POR_ID, VISTA_CONSULTAR_EMPLEADO_POR_ID, VISTA_RESULTADO_CONSULTAR_EMPLEADO_POR_ID,

	CONSULTAR_EMPLEADOS, VISTA_RESULTADO_CONSULTAR_EMPLEADOS,

	MODIFICAR_EMPLEADO, MODIFICAR_EMPLEADO_ID, VISTA_MODIFICAR_EMPLEADO_ID, VISTA_MODIFICAR_EMPLEADO, VISTA_EXITO_MODIFICAR_EMPLEADO, VISTA_FALLO_MODIFICAR_EMPLEADO,

	CONSULTAR_EMPLEADOS_POR_DEPARTAMENTO, VISTA_CONSULTAR_EMPLEADOS_POR_DEPARTAMENTO, VISTA_RESULTADO_CONSULTAR_EMPLEADOS_POR_DEPARTAMENTO

}